### ISSUE TITLE
Shiplist Editing

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#10]
Less of an issue and more of a feature request.  Editing the Editor shiplist based on ones provided like the craft packs I'm sure youre familiar with provide.

**Comment by MikeG621** [comment]
I'm going to need more information.  Are you looking for a means to
override the built-in craft list with something like the XWAUP list, or a
total conversion craft list?

--
Michael Gaisser
850-396-4535

**Comment by ual002** [comment]
Yea, either.  I see a shiplist txt file in the DL with the editor, but in the editor the shiplist when selecting a class looks vanilla.

**Comment by MikeG621** [comment]
Shiplist.txt file?  The only txt files I have in the zip file are the
Readme and license.  AlliED has a Ships.txt file, but it's not something
I've messed with.

So a custom shiplist is doable, though it's not a quick fix since it needs
to be platform-specific, also include abbreviations and it's hooked in all
over the place.  I know how I'm going to do it, will start that after I
take care of the map for #11.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
I have the overrides working for TIE, I should have XvT and XWA updated
tomorrow.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
Code changes committed, will also be putting together templates to package with the release.

**Comment by MikeG621** [comment]
v1.4 released.
