### ISSUE TITLE
Unhandled exception has occurred in your application

### ISSUE THREAD

**Issue by NLG24** [MikeG621/YOGEME#100]
I was uninstalling and then reinstalling some files to X-Wing Alliance Upgrade and then TIE Fighter Total Conversion. But when I tried opening YOGEME, it opened up an error window along with details shown in the zip file. It reads "Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. Object reference not set to an instance of an object."

Every time I click Continue, YOGEME is active as a background program but not visible in a desktop window.

[YOGEME Error.zip](https://github.com/MikeG621/YOGEME/files/14087733/YOGEME.Error.zip)

**Comment by MikeG621** [comment]
It's getting tripped up initializing with SuperBackdrops, looks like it's
trying to process something in the Form before it's finished being built.
I'll try to replicate it on my end.

**Comment by NLG24** [comment]
I thought this was acting up because of a change I did. Take your time. I'll be patient. =]

**Comment by NLG24** [comment]
Just a moment ago, I was testing something and I found a curious case. YOGEME appears to be working fine under the original X-Wing Alliance (without mods XWAU and TFTC). I checked the Options dialog menu and the checkbox "Apply DTM Super Backdrops to new missions" is checked and cannot be changed manually. But if you try to open YOGEME with mod changes (TFTC for my case), it will open up the error message I sent the images and message.txt earlier today. I'm wondering how to manually uncheck the option "Apply DTM Super Backdrops to new missions" when working on missions under XWAU 6.0 and TFTC 1.3.4 if I cannot reach the dialog box due to the error.

**Comment by MikeG621** [comment]
Under vanilla, the checkbox is disabled because Super Backdrops isn't
detected so it effectively doesn't do anything.
Do you have any other platforms installed?  If you could start a new TIE or
XvT mission, you can access the options from there and then uncheck it.  If
not, then when XWA is at vanilla and you can get to Options, uncheck "Only
allow editing for installed platforms".  Then once XWAU/TFTC are active and
YOGEME won't let you get to XWA, you'll be able to open as TIE or XvT so
you can get to the Options again to uncheck it.  A workaround until I can
figure out why your install is acting up.

What version of YOGEME are you running right now?  Help > About.

**Comment by NLG24** [comment]
It's the latest version of YOGEME. I don't have other platforms installed. I'll see if this works.

**Comment by NLG24** [comment]
It works! Took me a while to use your suggestions for I was busy doing something else and away from my computer. I want to thank you sincerely for the troubleshooting.

**Comment by MikeG621** [comment]
And right on cue, I just got it to crash on my end.  Did you change the
default craft's type to Backdrop?  The path that's leading to the crash
only occurs if there's already a backdrop when SBD is applied.

**Comment by NLG24** [comment]
I did a few days ago. I thought I set it to Backdrop just for shortcut in setting up backgrounds for custom missions.

**Comment by MikeG621** [comment]
If SBD is installed and checked on startup, it invisibly clicks the "Apply
SBD" menu item.  Backdrops have to exist *after* the SBD skybox, so it
copies the existing one to the end.  The problem is parts of the Copy
routine need info from the GUI, but on a new mission startup it doesn't
exist yet when that happens.

Corner case, but I can rework it so it'll work as intended, with your
default Backdrop FG after the skybox.

**Comment by NLG24** [comment]
I only wanted to move past the error, but you can if you want to. Again, thank you very much for technical solution(s).

**Comment by NLG24** [comment]
Everything seems normal, thanks to your solutions.
