### ISSUE TITLE
Words ending with ] (end bracket) not highlighted despite being included in [ ]

### ISSUE THREAD

**Issue by NLG24** [MikeG621/YOGEME#102]
Hello, I'm Nicholas,

I wanted to thank you for fixing the major bug that didn't allow me to use YOGEME months ago.

I found another bug concerning highlighted text shown in mission briefings. In Commander's Briefing text of a mission briefing (not the Map Briefing w/ animations), even if you bracketed certain words and add a period ( . ) next to the this end bracket ( ] ), the word with the end bracket ends up not being highlighted at all as shown in the screencaps below. The same can be said for Mission Debriefing text as well. Words next to ] ends up not being highlighted despite being included within the [ ] .

![image](https://github.com/MikeG621/YOGEME/assets/158083197/f28dd926-76af-4f2e-8816-485d05951147)

![image](https://github.com/MikeG621/YOGEME/assets/158083197/eadf0b09-d6bc-4fbd-aa3d-a747aadb4568)

If you wish for me to provide more screencaps, I can do that.

**Comment by MikeG621** [comment]
Seems to be occurring if any character is immediately after ']'.

There's no special processing of those characters in YOGEME for XWA, those
are stored as-is.  That leads to the behavior being part of XWA itself, not
the mission file.

**Comment by NLG24** [comment]
This wasn't an issue before. I think this problem occurred from the update before the previous one, Before version 1.15.7.

**Comment by MikeG621** [comment]
And yet if I take a vanilla mission from '99 and use a hex editor to ensure
there is something other than a space after the ']', the behavior occurs.
It has nothing to do with YOGEME.  The only thing YOGEME does is replace
the "$" in the raw text with line breaks, everything else is left untouched.

I checked every original mission, and the [ ] highlighting was only used a
couple times, and even then only in the Mission Failed Debrief.  It's not
like TIE, which used it all the time.  It's entirely possible it's a latent
bug in XWA since this function was never used in the pre-flight briefing.
The other option is that one of the hooks or ddraw updates changed
something; I don't have a pure vanilla install ready to test that right now.

**Comment by MikeG621** [comment]
Confirmed to occur in vanilla unmodified missions, pre-briefing and post-mission text, not a problem with YOGEME

**Comment by NLG24** [comment]
So, it must be TFTC project-related bug. I pray there is a fix to this as time goes on.

Thank you again for the technical support.
