### ISSUE TITLE
Importing OPTs

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#12]
Not sure if I saw you mention this at some point in the XWAup forums, but I do think getting the editor to pull OPT files for display in the editor instead of icons, or even hard coded wireframes like in ALLiED would drastically increase this editor's value and usability.

**Comment by MikeG621** [comment]
I did intend to import the OPTs directly at some point, especially since
then it would pull custom ships, be it from XWAUP or another source, but I
never got around to creating an OPT processor.  My true vision for the map
editor was not just a 2D interface, but rather a 3D rotatable space like a
CAD program so you could see exactly how the ships would appear next to
each other.  That would be the best way to place ships near bases such as
Platforms or Shipyards.

This would certainly be a longer-term item to work on, although with the
renewed interest and traffic on git I may look into working on this again.

--
Michael Gaisser
850-396-4535

**Comment by foonix** [comment]
I'm working on an OPT reader.  My current code only supports Tie and is pretty nasty (I'm not a professional c# developer), but if it'll be more useful than a spec to you, you're welcome to it.

**Comment by ual002** [comment]
Yea, I have no skill in this regard, but the 3D space editor would be amazing.  But definitely an opt reader to start.  Most of the custom DSUCP craft have no models in Troy's editors and make for a lot of guess work in placing crafts.

**Comment by MikeG621** [comment]
Yeah, that's why I had hoped to use an opt reader instead of fixed
wireframes, to take into account custom models. That's also part of the
reason why the map images were left as separate files instead of embedded,
so they could be customized.

For the most part at least the new models tend to be replacing similar
models, so the sizes should be close.

I'm keeping an eye on an opt reader project, so if that continues at a good
clip that'll help the possibility of this approaching reality.

On Nov 10, 2017 18:20, "ual002" <notifications@github.com> wrote:

Yea, I have no skill in this regard, but the 3D space editor would be
amazing. But definitely an opt reader to start. Most of the custom DSUCP
craft have no models in Troy's editors and make for a lot of guess work in
placing crafts.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/MikeG621/YOGEME/issues/12#issuecomment-343621181>, or mute
the thread

**Comment by JeremyAnsel** [comment]
Hello,
Have you considered using https://github.com/JeremyAnsel/JeremyAnsel.Xwa.Opt ?

**Comment by MikeG621** [comment]
No, I haven't looked at yours, Jeremy.  TBH I should've thought to look to
see what you were using since I know about your OPT editor.  Yours is
primarily for XWA though, correct?  Jason said his was TIE and I haven't
messed with the OPT format enough to know if there's meaningful differences
between the engines or if it could be easily managed with a single reader.

--
Michael Gaisser
850-396-4535

**Comment by JeremyAnsel** [comment]
Mine can read OPT files from all games of the series.

**Comment by MikeG621** [comment]
v1.7 released with OPT wireframes for the map
