### ISSUE TITLE
Work reduction widgets.

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#13]
1.  (XWA) Having a Super backdrops star field auto population widget to add all the backdrops in the right spots with the right settings would be a nice addon widget and work flow reducer.  Until such time that someone figures out how to make the default starfield brighter and more populated those .DAT file "matte painting" starfields are really part of the editing experience now.

2.  A similar hyperbouy wizard to ALLiED would also be good.  

There are a lot of functions in ALLiED I am just now learning to use in my almost 20 years of off and on again use.  Flightgroup and mission order clipboards are amazing.  These types of features will set YOGEME apart.  If the editor can do everything ALLiED can do, and then later even more, it is likely something that can replace ALLiED all together.  Amazing work so far.  Still amazes me someone actually tried this.

**Comment by MikeG621** [comment]
1) I'll look at the forums to dig out the details on this as I don't
remember off the top of my head.  If it's something that can be setup in
the stock game, then I'll just add it to the mission template, like how I
have the light source backdrop right now.  If It requires the XWAUP or
another patch from Jeremy, then I'll have to hook it in differently.

2) This is something that I can implement easy enough.

When I set out to make YOGEME, I didn't want to just make a
TFW/XvTEd/ALLiED clone.  Granted, the main interface wound up being similar
but in the end I couldn't think of a different/better way to do it.  I was
focused mainly on adding the "Unknown" mission functionalities that we'd
uncovered over the years and getting the briefings / TIE Officer previews
to be as close to pixel-perfect as possible.  A single program to do
everything, without any in-game surprises.  That's why some things that
AlliEd has like the Goal Summary (which was recently added by another
contributor anyway) weren't added, because I didn't want to just rip them
off.

Side note about the clipboards; due to how I have that implemented, the
clipboard items write to a file, which means you can have multiple YOGEME
windows open with different missions and copy/paste between them.

Now that it's been 20-ish years and ALLiED isn't being worked on, I'm not
as opposed to adding in those "missing" features.  I'm thrilled that more
people are looking at it, especially since YOGEME itself is 10 years old
now.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
Hyperbuoy dialog has been added

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
v1.4 is released with the hyperbuoy wizard.  Going to leave this open for now, as I haven't taken a look at the backdrops yet.

**Comment by MikeG621** [comment]
Released with Super Backdrops
