### ISSUE TITLE
Test function in nondefault installation directory

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/YOGEME#20]
In a multiple-installation environment as discussed in [this thread](http://www.xwaupgrade.com/phpBB3/viewtopic.php?f=15&t=11853), the test function (which, as an aside, might be better presented as a button rather than a non-menu entry in the menu bar) always uses the XWingAlliance.exe in the default installation directory rather than the one in the installation area where the mission being edited resides.  This results in some confusing and inconvenient behavior, since the mission loaded (if it loads at all) won't be the one you're editing.

**Comment by MikeG621** [comment]
It's based on the installation path stored in the Options dialog which are
originally detected via the registry, since it can't be assumed that every
mission file you open is located in a valid \MISSIONS directory that's part
of a full installation.  There's also this thread
<http://www.xwaupgrade.com/phpBB3/viewtopic.php?f=9&t=11839&p=153142> where
a different type of multi-install is discussed.  I can't guarantee that the
directories being used are a full install or just a partial used for modded
files.

That said, if you're working in a full mod install and want to work in
there, if you change the directory in the Options dialog everything should
work normally using your selected install.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
Test menu item now listed under Tools so it's less likely to be accidentally pressed, will launch the platform according to the mission file's location if possible.
