### ISSUE TITLE
Live Backdrop selector

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#26]
In the same vein of using JeremyaFr's OPT viewer to somehow display installed opts on the map, a dat viewer that allows you to select your dat files for backdrops, reads them in a live sense and then spreads them out in a pallete like Allied would be nice, features would include a button to swap between all the available shadow states at once as well.

**Comment by MikeG621** [comment]
The backdrop dialog already loads the installed backdrops, and shows shadow
options, or are you looking for something else?

(From phone)

**Comment by ual002** [comment]
Ok, i must have been using an outdated version.  Do you have the ability to select specific dats for each type of backdrop.  With the backdrop hook, replacing those on a per mission basis is pretty easy?

**Comment by MikeG621** [comment]
No, it doesn't pick the dats themselves just what's currently installed, so
say you installed Super Backdrops, that would display instead of vanilla. I
can look into detecting and implementing the hook though, if it can specify
dats within the mission (I admit I'm not as familiar with his hooks)

(From phone)

**Comment by ual002** [comment]
Yea, the call to replace a specific dat (Backdrop, nebula, galaxy,planet,etc) would live in a .ini file with the same name as the mission.  So if you build in support for yogme to read and maybe even edit those files, whatever changes in them could be properly reflected in Yogme to accurately reflect what will show up in game for that specific mission.  Some notable things that can be done are FG color changing (Which you already support beyond the default 4), opt replacement, backdrop replacement and more.

**Comment by ual002** [comment]
And to update, I get an error when I try to adjust existing backdrops.  Additionally,  the apply superbackdrops wizard is greyed out.  This is on 1.5.1

![image](https://user-images.githubusercontent.com/7959255/61255570-c3fd4380-a72e-11e9-8160-92529f3d13b0.png)

**Comment by MikeG621** [comment]
The SuperBackDrops detection is just based on "File.Exists(_xwaPath +
"\\BackupDTMSB\\XwingAlliance.exe")" if XWA is installed, then the menu
item is enabled on startup.  Check what you have set in the Options dlg for
the XWA install path and if that's the install that you have SBD installed
to.

That particular error message should be from ImageFormat.Dat, initializing
a Collection either with more than 200 base images, or more than 200
variants/shadows/whatever for a given image.  I had originally picked that
arbitrary limit since nothing came close to that at the time (originally
wrote that one back in '09).  I suppose I should make that limit the true
32,767, since those are int16 in the format.
--
Michael Gaisser

**Comment by MikeG621** [comment]
Try replacing the Dat dll with this one, should fix that.  Limit is now 256, since the FG fields are just bytes.
[Idmr.ImageFormat.Dat.dll.zip](https://github.com/MikeG621/YOGEME/files/3397673/Idmr.ImageFormat.Dat.dll.zip)

**Comment by ual002** [comment]
Ok, so for some reason it defaulted to the missionverify.exe, when I changed it it seemed to work.

**Comment by ual002** [comment]
The viewing window seems small though

**Comment by MikeG621** [comment]
For XWA it should be displaying at 1:1. With the default DATs it might seem
small, but I've got SBD enabled on my end. I'm TDY now so it'll be a couple
days until I can look into anything.

(From phone)

**Comment by ual002** [comment]
I mean its only showing the upper left corner of the image

**Comment by MikeG621** [comment]
Attach a screenshot please

**Comment by MikeG621** [comment]
Also, for the DAT you're trying to use, how many different backdrops are
there, what's the maximum image size, and what are you replacing? (Since
XWA bounces around several DATs, trying to make sure you're not running
into other limits, too)
--
Michael Gaisser

**Comment by MikeG621** [comment]
Went ahead and just made the XWA backdrop dialog larger to display 512px
full-time instead of relying on the SuperBackdrops detection.  Since you
said it was cutoff and you had issues with SBD, I'm betting it was still
sized for 256px.

Also removed the image dimension limits entirely from the DAT dll itself.
--
Michael Gaisser

**Comment by MikeG621** [comment]
Also changed the SBD detection to looks for the DTMSBReadme instead of the
backup.  I had used the standalone location, where if it's installed by
XWAUCP the directory's different.  That'll fix that particular issue for
you.
--
Michael Gaisser

**Comment by MikeG621** [comment]
Do you have a custom DAT that isn't part of SBD or Planet2 ready to go?
Something that'd be obvious that it was loading due to the hook so I can
make sure YOGEME is pulling it in correctly.  Right now it'll load the
defaults, look for the base Resdata.txt, then load the files per the hook.
--
Michael Gaisser
