### ISSUE TITLE
Crash on first run if games are not present or not completely installed

### ISSUE THREAD

**Issue by chrisforbes** [MikeG621/YOGEME#29]
I attempted to launch the 1.62 release build, but it would fail silently.

Built from source instead, and found that the initial settings write is throwing ArgumentNullException if BoP is not found (in Settings.cs:465).

This then leads to writing an incomplete settings file which will cause settings load to fail on subsequent attempts.

Similar issue (at Settings.cs:491) if XWA is not completely installed (in this case, I had the files present from the Steam version but initial setup (which adds all the required registry keys) was not done.

**Comment by MikeG621** [comment]
Hmm, that's odd since those paths default to an empty string, so it
shouldn't throw null.  I wonder if Steam is doing a partial install prior
to first run, so it detects the "Steam App ######" key but the
"InstallLocation" value isn't set yet, since that then could return null.

Okay, easy enough to add a null check to that prior to write.
--
Michael Gaisser
