### ISSUE TITLE
Error when copying a FG

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#32]
When I attempt to copy a flight group by clicking on the "CopyFlightGroup" button, I get this error in the picture provided.

![image](https://user-images.githubusercontent.com/43460482/74497264-08ea8380-4e92-11ea-887a-1aa4b400cfd3.png)

**Comment by bguthrie1** [comment]
Never mind. I can't say what exactly fixed the issue but I had to replace the pinned shortcut on my taskbar, which is weird since the path didn't change and the application was still opening up normally.

**Comment by MikeG621** [comment]
The bin path is wrong.  Where is the YOGEME.exe located, and how are you
launching it?

**Comment by bguthrie1** [comment]
The YOGEME exe is in my onedrive folder. I'm launching it from my taskbar but at the time, opening it directly from the folder or from the taskbar still gave the same error.

**Comment by bguthrie1** [comment]
Now that I think about it, there seems to be other issues such as being unable to copy a FG from one instance to another instance of YOGEME. But it works fine if its not launched in Onedrive. So it appears Onedrive is the problem.

**Comment by MikeG621** [comment]
What's happening is when YOGEME is being launched via Onedrive, the
"working directory" isn't initialized properly so instead of looking for
the BIN file where YOGEME itself is located, it's using the system default,
which is a protected directory.  Onedrive isn't a normal folder on your
computer, so I'm not sure if there's a way to get that to work properly.
It'd be interesting to see if there's any other side effects being in there
that's not related to the clipboard functions.
--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
I've made the BIN and help file paths explicit so when the working
directory is different (launched via OneDrive or other special mechanisms)
it'll still located them properly.  Will be in the next release.
--
Michael Gaisser
850-396-4535
