### ISSUE TITLE
Features for first time visitors

### ISSUE THREAD

**Issue by RedDragonWebDesign** [MikeG621/YOGEME#38]
- Consider adding screenshots to readme.md.
- Consider adding demo/example files for each type of mission file in a folder named demo. I wanted to load some for Tie Fighter to see how the program works.
- edit: Mentioning the yoegme.chm in the readme.md would be good too. I am not familiar with .chm files so I didn't know that was clickable. It is packed with screenshots and great information.

I'm eager to explore the program. Little things like this would make it easier : )

**Comment by MikeG621** [comment]
If you want to learn, then "yogeme.chm", the help file, is where you need
to look.  That has information on how the program works, including
screenshots.  The Readme is more for documenting the history so that's just
plaintext.

Demo files, I'll think about it.  The original intent was that if you were
looking to edit for a platform, you'd have that platform installed and
therefore have all of the missions that come with it.  That's why by
default, you cannot edit platforms that aren't installed (unless it can't
find anything) since it can't be tested (I've had people submit custom
missions they made that were so broken, they obviously never flew it).
There's a lot of different functionality that can be wrapped into a
mission, it would likely take several for each platform to be able to
convey everything.  I've been doing this for so long, it's hard for me to
think of it as if I was coming in with nothing and starting from scratch.
--
Michael Gaisser

**Comment by Haamre** [comment]
@MikeG621 Hello Mike,
I'm not sure if it's just me, but after having downloaded the whole files group (via the git download button at the top of the list), the help file doesn't seem to work. It opens, it has the menu listed on the left side - but when you click on any of it, there's no text in the field to the right shown.

Additionally, from the readme file - it seems there should be some executable file located within the file list, correct? I don't see any - there are only source files present. Could you please verify, if the content of the currently available list of files is completed, and if so - how exactly should we be launching the editor?

Kind regards,
Mike

**Comment by MikeG621** [comment]
That's because you're downloading the source, and not the release package.
You need to use the Releases <https://github.com/MikeG621/YOGEME/releases>
link on the right side to grab the zip file.  There's a link directly to
the current 1.7 release visible on the right side as well.
--
Michael Gaisser

**Comment by MikeG621** [comment]
Placed a note in the Readme to open the CHM.
