### ISSUE TITLE
Old X-Wing Conversion 4.0 to XWA

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#42]
Hi,

Seem that the old "X-Wing Conversion 4.0" work partially in XWA

https://forums.xwaupgrade.com/viewtopic.php?f=15&p=179175#p179175

But If I load a old pilot of "X-Wing Conversion" the missions don't load.

Do you known if is possible port the old "X-Wing Conversion" missions and pilots to XWA ?

Is possible do a batch compatibility fix converter that bypass the crash ?

I have count >150 missions and if is possible solve the problem with a easy batch fix, can be very usefull.

**Comment by MikeG621** [comment]
I don't know anything about those Converters and they are not related to
YOGEME in any way.  As such I don't know what you're referring to when you
say "crash".
--
Michael Gaisser

**Comment by MikeG621** [comment]
I don't know what the upper limit of how many missions XWA can load or how
many can be saved in the pilot file.  Generally you wouldn't load all 100
custom missions at once anyway since you wouldn't be able to select which
ones to fly, unless you're talking about a 100-mission long campaign, which
really should be loaded as several smaller campaigns.  That's why pilot
editors won't go that far, because loading an entire library of custom
missions all at once is bad practice.
--
Michael Gaisser
