### ISSUE TITLE
Backdrop color picker

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#46]
![image](https://user-images.githubusercontent.com/7959255/107730210-705f2d00-6cb8-11eb-9dea-951a9066e6ab.png)
A color picker to select its RGB value would be handy

**Comment by MikeG621** [comment]
Are you thinking #FFFFFF color, or in a "X.X X.X X.X" format to use for a
backdrop light source?

**Comment by MikeG621** [comment]
Mouse over the image will update a small color preview, clicking will update the color label in "255 255 255" format.  On "OK" it'll be copied to YOGEME's internal clipboard so it can be pasted (via Ctrl+V or menu) into the FG name in the "0.00 0.00 0.00" format (trailing zeros are truncated).

Pasting cannot be done with the toolbar, since that removes focus.  Also cannot be done with Windows' normal R-click since it's not using the system clipboard.  May completely redo the clipboard to use the system at some point.

**Comment by MikeG621** [comment]
Published in v1.11
