### ISSUE TITLE
xwing conversion missing data

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#53]
Hi Mike,

I have converted different files from xwing to xwa here one example:

[test_YOGEME.zip](https://github.com/MikeG621/YOGEME/files/6212106/test_YOGEME.zip)

and I see there are some missing informations from original xwing file.

For example: missing goals description, the mission description is hide, etc...

I general I see "Waylon" conversion show more informations some are probably added manually and other are missing.

The goals conditions of "Waylon" and "YOGEME" conversion are differents I don't known what is the correct conversion.

In the "YOGEME" briefing I don't see the ships, while in "Waylon" I see correctly the ships.

I ask you if you can do a quick verify to check if is possible extract more informations by original file and if the conditions are correct.

Thanks !

**Comment by MikeG621** [comment]
The goals conditions are exactly the same.  I see the missing Time Limit
which the author chose to explicitly ignore, but that's it.  I don't see
anything else that's actually missing.
--

**Comment by luca2125** [comment]
Hi Mike,

I send more specific details:

![1](https://user-images.githubusercontent.com/55355625/112714856-de645a00-8edc-11eb-8eb1-6463fe78cc0b.png)

as you can see the descriptions are missing (including mission description where the first char is '#').

Here a video that show the briefing:


https://user-images.githubusercontent.com/55355625/112714916-0c499e80-8edd-11eb-8dbc-8cb29302a7e4.mp4

as you can see there no description and there is no ships.

Please let me known.

**Comment by MikeG621** [comment]
The descriptions are done manually, since they're built from the briefing.
Working as intended, nothing to do there.

There are no ships because the camera is moved off-screen.  That's a bug I
found from the last time you asked; something'e wrong with the scaling and
this problem only appears with converted missions since XWA does it
completely differently.  There's a second issue where YOGEME is not
displaying the XWA briefing correctly; it looks like it's supposed to, but
as you can see it's not what in-game looks like.  I've got that part mostly
fixed (with my debug build the briefing looks blank), but I'm still trying
to tune that conversion so everything will be located properly.
--

**Comment by luca2125** [comment]
Thank you Mike, I don't sure if can be useful, In the the zip file I have included the the some mission converted with another tool done in 2015 that are not bug free, but for briefing I hope can be useful.

**Comment by MikeG621** [comment]
Updated with fixes, works in my testing.
