### ISSUE TITLE
xwing conversion seem different from original

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#54]
Hi Mike,

Please excuse me for disturb again.

In the meantime I have compared more deep YOGEME conversion with original and I see some difference:

![arrival_depature](https://user-images.githubusercontent.com/55355625/112734000-62512d00-8f43-11eb-81fb-444dfcd05c63.png)

Original file: arrive via mothership, but the YOGEME arrive via hyperspace.

![orders](https://user-images.githubusercontent.com/55355625/112734020-801e9200-8f43-11eb-8a99-d1609d95052b.png)

Original file: The primary target is none, but the YOGEME primary target  is not none.

Please let me know if are bugs or are normal situations.

Apart this another difference but probably is not important:

![teams](https://user-images.githubusercontent.com/55355625/112734093-f6bb8f80-8f43-11eb-8789-8a78ec5f4458.png)

You have inserted the 3° message as "standard" message that I suppose is not a problem.

Best Regards

Marco

**Comment by MikeG621** [comment]
Your Allied conversion was to BoP format, not XWA.

That said, the arrival doesn't matter since it starts the mission in play,
it doesn't "arrive" at all.  In the original mission it even says the
mothership is "none".

Orders in X-wing are different than the other games.  YOGEME does it
correctly; the primary order is to attack Imperial starfighters, then the
additional targets in XW are the Secondary Targets in every other platform.

For the end of mission message, that's an error on Allied's part.  In XW
there are 3 EOM messages, however in the other platforms there are only 2.
To move the third one to Secondary is a completely different trigger, and
in fact you would never see it.

Again, there is nothing wrong.
--
