### ISSUE TITLE
1.11.1 Uninstaller flagged by Chrome / Windows Security

### ISSUE THREAD

**Issue by justinwasilenko** [MikeG621/YOGEME#62]
I just tried to download 1.11.1 however both Chrome and Windows Security tried to block it. Wanted to make sure the repo didn't get hacked.

![Capture](https://user-images.githubusercontent.com/11709400/129463409-b1777be3-aa08-4ba6-9beb-17369525def3.PNG)

**Comment by MikeG621** [comment]
False positive, the uninstaller is the same that I've been using for years,
only recently has it started to get flagged on occasion.
--
Michael Gaisser

**Comment by MikeG621** [comment]
I re-released 1.11.1 with a new build of the Uninstaller, give that a try and see if that comes through clean.

**Comment by RandomStarfighter** [comment]
Windows Defender is still flagging the uninstaller in 1.11.1.
Going back through my version archive, 1.7 seems to be clean.  However, Windows Defender is flagging the uninstaller in version 1.8.2, and every version since.  Running a binary file comparison, something was changed in the uninstaller after 1.7.  Whatever it is, Defender doesn't like it.  I don't remember having any problems with them before, but it seems to be a new issue that's arisen in the past couple months.

**Comment by MikeG621** [comment]
That's just it, the only thing that "changed' originally was that I
recompiled it for the first time in 10 years, using a current .NET
framework.  The program itself is the same between the "clean" version and
what Defender is complaining about (which doesn't flag it on my end, btw).
The whole thing was only about 50 lines of code, and the one I just built
is more like 30.
--
Michael Gaisser
