### ISSUE TITLE
Pulling the correct Backdrop DAT info

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#72]
Beside the issue with backdrop errors popping up, Im trying to figure out the best system for yogme to recognize which backdrop file a mission is using usually defined in the mission.ini.  If the mission is using backdrops other than those defined in the default planet.dat, say the mission.ini is using planetTFTC.dat, the mission in yogme will show the backdrops for planet.dat.  Is there a way the yogme could read the mission INI or have a drop down to choose the .dat file to reference?

**Comment by MikeG621** [comment]
Yeah, I can have it skip comments. The title wasn't in the version I have,
so didn't have that to go on. Is ";" going to be the only comment marker
used?

**Comment by ual002** [comment]
probably, that seems to be the one ace likes to use, but if you can think of other common use types.  (Im no coder)

**Comment by MikeG621** [comment]
Both added in cb45f6e.

**Comment by MikeG621** [comment]
Didn't realize you asked a different question before really replying to #71 , so reopened.

The problem with trying to figure out where a DAT actually came from is that any DAT file can overwrite the originals.  That's in fact what the XWAUP/TFTC/etc files do; they redefine existing images so the new backdrops are used instead.  Once the images are loaded, there's no record of where they came from.

YOGEME does load those files, so you'll see planetTFTC.dat images if it's called out via mission.ini or added to RESDATA.  So I'm not sure what your original question is.  If hooks_backdrops.dll is present, then it'll search for additional DAT resources.  If "\Missions\[Mission]_resdata.txt" is present it will read from there, otherwise it will read from "\Missions\[Mission].ini"
