### ISSUE TITLE
Waypoint Drag issue

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#83]
I've made a video as its hard to explain.

https://youtu.be/oAJxf-BFbgE

**Comment by MikeG621** [comment]
Are there any hyperpoints or orders to switch regions already setup for
that FG?

**Comment by ual002** [comment]
I believe so

**Comment by MikeG621** [comment]
Can you send me or attach the particular mission you're seeing this on?  I'm having trouble replicating it.  I'm betting it has to do with hypering, since there's "virtual" waypoints that are calculated for the exit and aim points

**Comment by ual002** [comment]
[Optional_Combat_Missions.zip](https://github.com/MikeG621/YOGEME/files/11668198/Optional_Combat_Missions.zip)
Its one of the first couple missions in here.

**Comment by MikeG621** [comment]
Okay, so it's definitely related to the hyper, and I think the big thing right now is that the issues are occurring in the Home region, where you don't have a separate FROM hyper buoy since you're dual-purposing them.  It knows that the affected FGs have orders to hyper to that region, but it can't locate the primary buoy to determine the exit point (which uses WP1) so it's acting screwy.

There's also the issue of the waypoints for orders 2 and 3 not being enabled, so that's causing calculation failures with exit and aim points.

If dual-purpose buoys work fine in-game, I'll definitely add the ability to detect them.

**Comment by MikeG621** [comment]
Pretty sure I've got it sorted now.  Adding the check for the second
Designation fixed the WP1 selection, and I also discovered I could select
the virtual exit point regardless of the active order (which is what you
had been targeted instead of WP1), so now that's behaving properly.  Going
to play some more with it to see if I can break it any other way.

**Comment by MikeG621** [comment]
Closing for now, as most of the issues I was seeing are for player-controlled FGs that don't have orders, WPs, etc, but it's certainly better than it was.  Still thinking I may want to rewrite the whole thing some day since the hyper handling was scabbed on after the fact.
